cc_binary(
  name = 'write_db',
  srcs = 'write_db.cc',
  deps = [
    '#gflags',
    '//:leveldb',
  ],
)

cc_binary(
  name = 'read_db',
  srcs = 'read_db.cc',
  deps = [
    '#gflags',
    '//:leveldb',
  ],
)

