cc_test(
  name = 'iterator_test',
  srcs = 'iterator_test.cc',
  deps = [
    '//:leveldb',
  ]
)

cc_test(
  name = 'block_test',
  srcs = 'block_test.cc',
  deps = [
    '//:leveldb',
  ]
)

cc_test(
  name = 'filter_block_test',
  srcs = 'filter_block_test.cc',
  deps = [
    '//:leveldb',
    '//util:testutil',
  ]
)

cc_test(
  name = 'table_test',
  srcs = 'table_test.cc',
  deps = [
    '//util:testutil',
    '//:leveldb',
  ]
)

